// mf-react-display/src/App.js
import React, { Component } from 'react';
import './App.css';

class App extends Component {

  constructor(props) {
    super(props);
    this.state = {
      count: 0
    }
    this.updateDisplay = this.updateDisplay.bind(this);
    this.componentDidMount = this.componentDidMount.bind(this);
  }

  

  componentDidMount() {
    window.addEventListener('message', this.updateDisplay);
  }

  updateDisplay(event) {
    if(event.data !== null) {
      console.log(event.data.val)
      this.value = event.data.val
    } else {
      this.value = 0
    }
    this.handleCount(this.value)
  }

  handleCount(value) {
    this.setState({ count: value });
  }

  render() {
    return (
      <div className="App">
        <h4> Display </h4>
          <table>
              <tbody>
                  <tr><td>{this.state.count}</td></tr>
              </tbody>
          </table>
      </div>
    );
  }
}

export default App;

// mf-display/src/App.vue
<template>
    <div id="app">
        <h4> Display </h4>
        <table>
            <tr id="display-val">
                <p>
                  {{ value }}
                </p>
            </tr>
        </table>
    </div>
</template>

<script>
export default {
  name: 'App',
  data () {
    return {
      value: 0
    }
  },
  methods: {
    updateDisplay (event) {
      if(event.data !== null) {
        console.log(event.data)
        this.value = event.data.val
      } else {
        this.value = 0
      }
    }
  },
  mounted () {
    window.addEventListener('message', this.updateDisplay)
  }
}
</script>

<style scoped>
#app {
  font-family: Avenir, Helvetica, Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  color: #2c3e50;
}

table {
  border: 1px solid gray;
  width: 100%;
  padding: 10px;
}
</style>
